
help: targets

targets: checkrequired
	@echo
	@echo "******************************************************************************"
	@echo "* Makefile Targets"
	@echo "******************************************************************************"
	@echo "* "
	@echo "* => Publishing Targets:"
	@echo "*     make pdf              generate print book interior PDF"
	@echo "*     make betapdf          generate draft PDF suitable for beta readers"
	@echo "*     make draftpdf         generate draft monospaced PDF suitable for editing"
	@echo "*     make epub             generate ebook in .epub format"
	@echo "*     make mobi             generate ebook in .mobi format"
	@echo "*     make journal          generate book journal in PDF format"
	@echo "*     make all              generate pdf, epub and mobi targets"
	@echo "*     make veryall          generate all publishing targets"
	@echo "* "
	@echo "* => Cleaning Targets:"
	@echo "*     make clean            clean generated and intermediate files"
	@echo "* "
	@echo "* => Progress Targets:"
	@echo "*     make wordcount        show project word count (also \"make help\")"
	@echo "*     make logcount         log project word count"
	@echo "*     make progress         show daily progress"
	@echo "*     make logprogress      log daily progress"
	@echo "*     make lprogress        show last logged daily progress"
	@echo "* "
	@echo "* => Utility Targets:"
	@echo "*     make gitsnap          snapshot changed files in git"
	@echo "*     make spell            spell check all files"
	@echo "*     make spellchanged     spell check changed files"
	@echo "*     make chapter          add a new chapter file"
	@echo "*"
	@echo "* => Debugging/Help Targets"
	@echo "*     make targets          display this message (also \"make help\")"
	@echo "*     make variables        display configuration variables (also \"make environment\")"
	@echo "*     make toolpaths        display detected tool paths"
	@echo "* "
	@echo "******************************************************************************"
	@echo ""

.PHONY: help targets
